// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block_types.proto

package network

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is aa compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockHeader struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PreviousHash         []byte   `protobuf:"bytes,2,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	GasLimit             []byte   `protobuf:"bytes,3,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed              []byte   `protobuf:"bytes,4,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Height               []byte   `protobuf:"bytes,5,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MerkleRoot           []byte   `protobuf:"bytes,7,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	TxHashes             [][]byte `protobuf:"bytes,8,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	LeaderPubKey         *Point   `protobuf:"bytes,9,opt,name=leader_pub_key,json=leaderPubKey,proto3" json:"leader_pub_key,omitempty"`
	MinorPubKeys         []*Point `protobuf:"bytes,10,rep,name=minor_pub_keys,json=minorPubKeys,proto3" json:"minor_pub_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_types_6ab120560a854c01, []int{0}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockHeader) GetPreviousHash() []byte {
	if m != nil {
		return m.PreviousHash
	}
	return nil
}

func (m *BlockHeader) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *BlockHeader) GetGasUsed() []byte {
	if m != nil {
		return m.GasUsed
	}
	return nil
}

func (m *BlockHeader) GetHeight() []byte {
	if m != nil {
		return m.Height
	}
	return nil
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *BlockHeader) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func (m *BlockHeader) GetLeaderPubKey() *Point {
	if m != nil {
		return m.LeaderPubKey
	}
	return nil
}

func (m *BlockHeader) GetMinorPubKeys() []*Point {
	if m != nil {
		return m.MinorPubKeys
	}
	return nil
}

type BlockData struct {
	TxCount              int32          `protobuf:"varint,1,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	TxList               []*Transaction `protobuf:"bytes,2,rep,name=tx_list,json=txList,proto3" json:"tx_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockData) Reset()         { *m = BlockData{} }
func (m *BlockData) String() string { return proto.CompactTextString(m) }
func (*BlockData) ProtoMessage()    {}
func (*BlockData) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_types_6ab120560a854c01, []int{1}
}
func (m *BlockData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockData.Unmarshal(m, b)
}
func (m *BlockData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockData.Marshal(b, m, deterministic)
}
func (dst *BlockData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockData.Merge(dst, src)
}
func (m *BlockData) XXX_Size() int {
	return xxx_messageInfo_BlockData.Size(m)
}
func (m *BlockData) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockData.DiscardUnknown(m)
}

var xxx_messageInfo_BlockData proto.InternalMessageInfo

func (m *BlockData) GetTxCount() int32 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func (m *BlockData) GetTxList() []*Transaction {
	if m != nil {
		return m.TxList
	}
	return nil
}

type Block struct {
	Header               *BlockHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Data                 *BlockData   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	MultiSig             *Signature   `protobuf:"bytes,4,opt,name=multi_sig,json=multiSig,proto3" json:"multi_sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_types_6ab120560a854c01, []int{2}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetData() *BlockData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetMultiSig() *Signature {
	if m != nil {
		return m.MultiSig
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockHeader)(nil), "network.block_header")
	proto.RegisterType((*BlockData)(nil), "network.block_data")
	proto.RegisterType((*Block)(nil), "network.block")
}

func init() { proto.RegisterFile("block_types.proto", fileDescriptor_block_types_6ab120560a854c01) }

var fileDescriptor_block_types_6ab120560a854c01 = []byte{
	// 423 bytes of aa gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0xda, 0x6d, 0xd3, 0x4e, 0xca, 0x4a, 0x98, 0x2f, 0xb3, 0x20, 0x11, 0x95, 0x03, 0xbd,
	0x6c, 0x91, 0x0a, 0xff, 0x80, 0xcb, 0x4a, 0xec, 0x01, 0x19, 0xc1, 0xd5, 0x72, 0x5b, 0x2b, 0xb1,
	0x9a, 0xd8, 0x91, 0x67, 0xb2, 0xa4, 0xff, 0x82, 0x3f, 0xc9, 0xff, 0x40, 0x76, 0xda, 0x12, 0xa1,
	0xbd, 0x65, 0xe6, 0xbd, 0x37, 0x7a, 0x79, 0xcf, 0xf0, 0x74, 0x5b, 0xb9, 0xdd, 0x41, 0xd2, 0xb1,
	0xd1, 0xb8, 0x6e, 0xbc, 0x23, 0xc7, 0x52, 0xab, 0xe9, 0x97, 0xf3, 0x87, 0x1b, 0xb6, 0xf3, 0xc7,
	0x86, 0xdc, 0x10, 0xbc, 0x79, 0x45, 0x5e, 0x59, 0x54, 0x3b, 0x32, 0xce, 0x0e, 0x81, 0xe5, 0x9f,
	0x11, 0x2c, 0xfa, 0x5b, 0xa5, 0x56, 0x7b, 0xed, 0x19, 0x87, 0xf4, 0x41, 0x7b, 0x34, 0xce, 0xf2,
	0x24, 0x4f, 0x56, 0x13, 0x71, 0x1e, 0xd9, 0x7b, 0x78, 0xd2, 0x78, 0xfd, 0x60, 0x5c, 0x8b, 0xb2,
	0x54, 0x58, 0xf2, 0x51, 0x9e, 0xac, 0x16, 0x62, 0x71, 0x5e, 0xde, 0x29, 0x2c, 0xd9, 0x1b, 0x98,
	0x17, 0x0a, 0x65, 0x65, 0x6a, 0x43, 0x7c, 0x1c, 0x09, 0xb3, 0x42, 0xe1, 0x7d, 0x98, 0xd9, 0x6b,
	0x08, 0xdf, 0xb2, 0x45, 0xbd, 0xe7, 0x57, 0x11, 0x4b, 0x0b, 0x85, 0x3f, 0x50, 0xef, 0xd9, 0x4b,
	0x98, 0x96, 0xda, 0x14, 0x25, 0xf1, 0x49, 0x04, 0x4e, 0x13, 0x7b, 0x0b, 0x73, 0x32, 0xb5, 0x46,
	0x52, 0x75, 0xc3, 0xa7, 0x79, 0xb2, 0x1a, 0x8b, 0x7f, 0x0b, 0xf6, 0x0e, 0xb2, 0x5a, 0xfb, 0x43,
	0xa5, 0xa5, 0x77, 0x8e, 0x78, 0x1a, 0xa5, 0xd0, 0xaf, 0x84, 0x73, 0x14, 0xec, 0x50, 0x17, 0xdd,
	0x6a, 0xe4, 0xb3, 0x7c, 0x1c, 0xec, 0x50, 0x77, 0x17, 0x67, 0xf6, 0x19, 0xae, 0xab, 0xf8, 0xd3,
	0xb2, 0x69, 0xb7, 0xf2, 0xa0, 0x8f, 0x7c, 0x9e, 0x27, 0xab, 0x6c, 0x73, 0xbd, 0x3e, 0x45, 0xb9,
	0x6e, 0x9c, 0xb1, 0x24, 0x16, 0x3d, 0xeb, 0x5b, 0xbb, 0xfd, 0xaa, 0x8f, 0x41, 0x55, 0x1b, 0xeb,
	0x2e, 0x22, 0xe4, 0x90, 0x8f, 0x1f, 0x53, 0x45, 0x56, 0x2f, 0xc2, 0xe5, 0x4f, 0x80, 0x3e, 0xe6,
	0xbd, 0x22, 0x15, 0x82, 0xa0, 0x4e, 0xee, 0x5c, 0x6b, 0xe9, 0x9c, 0x32, 0x75, 0x5f, 0xc2, 0xc8,
	0x6e, 0x21, 0xa5, 0x4e, 0x56, 0x06, 0x89, 0x8f, 0xe2, 0xdd, 0xe7, 0x97, 0xbb, 0x83, 0x0e, 0xc5,
	0x94, 0xba, 0x7b, 0x83, 0xb4, 0xfc, 0x9d, 0xc0, 0x24, 0x1e, 0x66, 0xb7, 0x21, 0xc1, 0xe0, 0x33,
	0xf6, 0x92, 0x6d, 0x5e, 0x5c, 0x74, 0xc3, 0x7e, 0xc5, 0x89, 0xc4, 0x3e, 0xc0, 0x55, 0xb0, 0x12,
	0x3b, 0xca, 0x36, 0xcf, 0xfe, 0x23, 0x07, 0x48, 0x44, 0x02, 0xfb, 0x08, 0xf3, 0xba, 0xad, 0xc8,
	0x48, 0x34, 0x45, 0x6c, 0x2d, 0xdb, 0xb0, 0x0b, 0x1b, 0x4d, 0x61, 0x15, 0xb5, 0x5e, 0x8b, 0x59,
	0x24, 0x7d, 0x37, 0xc5, 0x76, 0x1a, 0x5f, 0xd6, 0xa7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xda,
	0x45, 0x14, 0x11, 0xa4, 0x02, 0x00, 0x00,
}
