// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crypto_types.proto

package network

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point struct {
	X                    []byte   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    []byte   `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_crypto_types_ce9f9085b3a445e5, []int{0}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *Point) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

type PrivateKey struct {
	Prv                  []byte   `protobuf:"bytes,1,opt,name=prv,proto3" json:"prv,omitempty"`
	PubKey               *Point   `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateKey) Reset()         { *m = PrivateKey{} }
func (m *PrivateKey) String() string { return proto.CompactTextString(m) }
func (*PrivateKey) ProtoMessage()    {}
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_crypto_types_ce9f9085b3a445e5, []int{1}
}
func (m *PrivateKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKey.Unmarshal(m, b)
}
func (m *PrivateKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKey.Marshal(b, m, deterministic)
}
func (dst *PrivateKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKey.Merge(dst, src)
}
func (m *PrivateKey) XXX_Size() int {
	return xxx_messageInfo_PrivateKey.Size(m)
}
func (m *PrivateKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKey.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKey proto.InternalMessageInfo

func (m *PrivateKey) GetPrv() []byte {
	if m != nil {
		return m.Prv
	}
	return nil
}

func (m *PrivateKey) GetPubKey() *Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type Signature struct {
	R                    []byte   `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	S                    []byte   `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_crypto_types_ce9f9085b3a445e5, []int{2}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (dst *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(dst, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *Signature) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

type CommandOfWord struct {
	Msg                  []byte   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandOfWord) Reset()         { *m = CommandOfWord{} }
func (m *CommandOfWord) String() string { return proto.CompactTextString(m) }
func (*CommandOfWord) ProtoMessage()    {}
func (*CommandOfWord) Descriptor() ([]byte, []int) {
	return fileDescriptor_crypto_types_ce9f9085b3a445e5, []int{3}
}
func (m *CommandOfWord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandOfWord.Unmarshal(m, b)
}
func (m *CommandOfWord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandOfWord.Marshal(b, m, deterministic)
}
func (dst *CommandOfWord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandOfWord.Merge(dst, src)
}
func (m *CommandOfWord) XXX_Size() int {
	return xxx_messageInfo_CommandOfWord.Size(m)
}
func (m *CommandOfWord) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandOfWord.DiscardUnknown(m)
}

var xxx_messageInfo_CommandOfWord proto.InternalMessageInfo

func (m *CommandOfWord) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Ticket struct {
	PubKey               *Point     `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	SigOfWord            *Signature `protobuf:"bytes,2,opt,name=sig_of_word,json=sigOfWord,proto3" json:"sig_of_word,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_crypto_types_ce9f9085b3a445e5, []int{4}
}
func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (dst *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(dst, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetPubKey() *Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Ticket) GetSigOfWord() *Signature {
	if m != nil {
		return m.SigOfWord
	}
	return nil
}

type SignalOfStart struct {
	Mark                 int32    `protobuf:"varint,1,opt,name=mark,proto3" json:"mark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignalOfStart) Reset()         { *m = SignalOfStart{} }
func (m *SignalOfStart) String() string { return proto.CompactTextString(m) }
func (*SignalOfStart) ProtoMessage()    {}
func (*SignalOfStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_crypto_types_ce9f9085b3a445e5, []int{5}
}
func (m *SignalOfStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignalOfStart.Unmarshal(m, b)
}
func (m *SignalOfStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignalOfStart.Marshal(b, m, deterministic)
}
func (dst *SignalOfStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignalOfStart.Merge(dst, src)
}
func (m *SignalOfStart) XXX_Size() int {
	return xxx_messageInfo_SignalOfStart.Size(m)
}
func (m *SignalOfStart) XXX_DiscardUnknown() {
	xxx_messageInfo_SignalOfStart.DiscardUnknown(m)
}

var xxx_messageInfo_SignalOfStart proto.InternalMessageInfo

func (m *SignalOfStart) GetMark() int32 {
	if m != nil {
		return m.Mark
	}
	return 0
}

type Commitment struct {
	PubKey               *Point   `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Q                    *Point   `protobuf:"bytes,2,opt,name=q,proto3" json:"q,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commitment) Reset()         { *m = Commitment{} }
func (m *Commitment) String() string { return proto.CompactTextString(m) }
func (*Commitment) ProtoMessage()    {}
func (*Commitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_crypto_types_ce9f9085b3a445e5, []int{6}
}
func (m *Commitment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commitment.Unmarshal(m, b)
}
func (m *Commitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commitment.Marshal(b, m, deterministic)
}
func (dst *Commitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commitment.Merge(dst, src)
}
func (m *Commitment) XXX_Size() int {
	return xxx_messageInfo_Commitment.Size(m)
}
func (m *Commitment) XXX_DiscardUnknown() {
	xxx_messageInfo_Commitment.DiscardUnknown(m)
}

var xxx_messageInfo_Commitment proto.InternalMessageInfo

func (m *Commitment) GetPubKey() *Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Commitment) GetQ() *Point {
	if m != nil {
		return m.Q
	}
	return nil
}

type Challenge struct {
	GroupPubKey          *Point   `protobuf:"bytes,1,opt,name=group_pub_key,json=groupPubKey,proto3" json:"group_pub_key,omitempty"`
	GroupQ               *Point   `protobuf:"bytes,2,opt,name=group_q,json=groupQ,proto3" json:"group_q,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	R                    []byte   `protobuf:"bytes,4,opt,name=r,proto3" json:"r,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Challenge) Reset()         { *m = Challenge{} }
func (m *Challenge) String() string { return proto.CompactTextString(m) }
func (*Challenge) ProtoMessage()    {}
func (*Challenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_crypto_types_ce9f9085b3a445e5, []int{7}
}
func (m *Challenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Challenge.Unmarshal(m, b)
}
func (m *Challenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Challenge.Marshal(b, m, deterministic)
}
func (dst *Challenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Challenge.Merge(dst, src)
}
func (m *Challenge) XXX_Size() int {
	return xxx_messageInfo_Challenge.Size(m)
}
func (m *Challenge) XXX_DiscardUnknown() {
	xxx_messageInfo_Challenge.DiscardUnknown(m)
}

var xxx_messageInfo_Challenge proto.InternalMessageInfo

func (m *Challenge) GetGroupPubKey() *Point {
	if m != nil {
		return m.GroupPubKey
	}
	return nil
}

func (m *Challenge) GetGroupQ() *Point {
	if m != nil {
		return m.GroupQ
	}
	return nil
}

func (m *Challenge) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Challenge) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

type Response struct {
	PubKey               *Point   `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	S                    []byte   `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_crypto_types_ce9f9085b3a445e5, []int{8}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPubKey() *Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Response) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func init() {
	proto.RegisterType((*Point)(nil), "proj.point")
	proto.RegisterType((*PrivateKey)(nil), "proj.private_key")
	proto.RegisterType((*Signature)(nil), "proj.signature")
	proto.RegisterType((*CommandOfWord)(nil), "proj.command_of_word")
	proto.RegisterType((*Ticket)(nil), "proj.ticket")
	proto.RegisterType((*SignalOfStart)(nil), "proj.signal_of_start")
	proto.RegisterType((*Commitment)(nil), "proj.commitment")
	proto.RegisterType((*Challenge)(nil), "proj.challenge")
	proto.RegisterType((*Response)(nil), "proj.response")
}

func init() { proto.RegisterFile("crypto_types.proto", fileDescriptor_crypto_types_ce9f9085b3a445e5) }

var fileDescriptor_crypto_types_ce9f9085b3a445e5 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xb3, 0x2f, 0x50, 0x5e, 0xa6, 0x18, 0xcc, 0x9e, 0xf0, 0x66, 0x16, 0x8c, 0x9e, 0x20,
	0xd1, 0xbb, 0x37, 0x4f, 0xc6, 0xa8, 0xbd, 0x78, 0x6c, 0x4a, 0x59, 0x6a, 0x81, 0xfd, 0xc3, 0xec,
	0x16, 0xd9, 0xab, 0x9f, 0xdc, 0xec, 0x96, 0x12, 0x4d, 0xd0, 0x70, 0x9b, 0xe9, 0xcc, 0x3c, 0xbf,
	0xa7, 0x33, 0x0b, 0x34, 0x47, 0xa7, 0xad, 0x4a, 0xad, 0xd3, 0xdc, 0x4c, 0x34, 0x2a, 0xab, 0x68,
	0x5b, 0xa3, 0x5a, 0xb2, 0x11, 0x74, 0xb4, 0x2a, 0xa5, 0xa5, 0x7d, 0x20, 0xbb, 0x21, 0xb9, 0x24,
	0x37, 0xfd, 0x84, 0xec, 0x7c, 0xe6, 0x86, 0xff, 0xea, 0xcc, 0xb1, 0x07, 0x88, 0x35, 0x96, 0xdb,
	0xcc, 0xf2, 0x74, 0xc5, 0x1d, 0x3d, 0x87, 0x96, 0xc6, 0xed, 0xbe, 0xd9, 0x87, 0x74, 0x0c, 0x5d,
	0x5d, 0xcd, 0x7c, 0x31, 0x0c, 0xc5, 0xb7, 0xb1, 0x87, 0x2c, 0x27, 0x41, 0x3a, 0x89, 0x74, 0x35,
	0x7b, 0xe4, 0x8e, 0x5d, 0x43, 0xcf, 0x94, 0x85, 0xcc, 0x6c, 0x85, 0xdc, 0x13, 0xb0, 0xe1, 0xa1,
	0xcf, 0x4c, 0xc3, 0x33, 0x6c, 0x04, 0x83, 0x5c, 0x09, 0x91, 0xc9, 0x79, 0xaa, 0x16, 0xe9, 0x87,
	0xc2, 0xb9, 0x67, 0x0a, 0x53, 0x34, 0x4c, 0x61, 0x0a, 0x96, 0x42, 0x64, 0xcb, 0x7c, 0xc5, 0xed,
	0x77, 0x3a, 0xf9, 0x95, 0x4e, 0xa7, 0x10, 0x9b, 0xb2, 0x68, 0x04, 0xf7, 0x3e, 0x07, 0x75, 0xe7,
	0xc1, 0x56, 0xe2, 0x1d, 0x3e, 0x2f, 0xde, 0x14, 0xce, 0xd9, 0x15, 0x0c, 0xc2, 0xf7, 0xb5, 0x9f,
	0x31, 0x36, 0x43, 0x4b, 0x29, 0xb4, 0x45, 0x86, 0xab, 0x80, 0xe9, 0x24, 0x21, 0x66, 0x4f, 0x00,
	0xde, 0x6c, 0x69, 0x05, 0x97, 0xa7, 0x7a, 0xb9, 0x00, 0xb2, 0x39, 0xb6, 0x29, 0xb2, 0x61, 0x9f,
	0x04, 0x7a, 0xf9, 0x7b, 0xb6, 0x5e, 0x73, 0x59, 0x70, 0x3a, 0x85, 0xb3, 0x02, 0x55, 0xa5, 0xd3,
	0x3f, 0x44, 0xe3, 0xd0, 0xf1, 0x52, 0x2b, 0x8f, 0xa1, 0x5b, 0x0f, 0x1c, 0xd5, 0x8f, 0x42, 0xed,
	0xb5, 0xd9, 0x66, 0xeb, 0xb0, 0xcd, 0xfa, 0x1c, 0xed, 0xfd, 0x39, 0xd8, 0x3d, 0xfc, 0x47, 0x6e,
	0xb4, 0x92, 0x86, 0x9f, 0xf8, 0x47, 0x3f, 0x0e, 0x38, 0x8b, 0xc2, 0x13, 0xbb, 0xfb, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x33, 0x26, 0x76, 0x90, 0x78, 0x02, 0x00, 0x00,
}
