// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fetch.proto

package network

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is aa compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FetchRequest struct {
	FetchWhat            []byte     `protobuf:"bytes,1,opt,name=fetch_what,json=fetchWhat,proto3" json:"fetch_what,omitempty"`
	Sig                  *Signature `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fetch_bd7ff4de52789751, []int{0}
}
func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (dst *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(dst, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

func (m *FetchRequest) GetFetchWhat() []byte {
	if m != nil {
		return m.FetchWhat
	}
	return nil
}

func (m *FetchRequest) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func init() {
	proto.RegisterType((*FetchRequest)(nil), "network.fetch_request")
}

func init() { proto.RegisterFile("fetch.proto", fileDescriptor_fetch_bd7ff4de52789751) }

var fileDescriptor_fetch_bd7ff4de52789751 = []byte{
	// 136 bytes of aa gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4b, 0x2d, 0x49,
	0xce, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca,
	0x96, 0x12, 0x4a, 0x2e, 0xaa, 0x2c, 0x28, 0xc9, 0x8f, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0x86, 0x48,
	0x2a, 0x85, 0x70, 0xf1, 0x82, 0xd5, 0xc6, 0x17, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9,
	0x72, 0x71, 0x41, 0x04, 0xca, 0x33, 0x12, 0x4b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0x38,
	0xc1, 0x22, 0xe1, 0x19, 0x89, 0x25, 0x42, 0x2a, 0x5c, 0xcc, 0xc5, 0x99, 0xe9, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0xdc, 0x46, 0x42, 0x7a, 0x50, 0xa3, 0xf5, 0x8a, 0x33, 0xd3, 0xf3, 0x12, 0x4b, 0x4a,
	0x8b, 0x52, 0x83, 0x40, 0xd2, 0x49, 0x6c, 0x60, 0xc3, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xed, 0x50, 0x4c, 0x37, 0x88, 0x00, 0x00, 0x00,
}
