// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serializable.proto

package network

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageHeader int32

const (
	MessageHeader_ACCOUNT         MessageHeader = 0
	MessageHeader_BLOCK_HEADER    MessageHeader = 1
	MessageHeader_BLOCK_DATA      MessageHeader = 2
	MessageHeader_BLOCK           MessageHeader = 3
	MessageHeader_TRANSACTION     MessageHeader = 4
	MessageHeader_TIMESTAMP       MessageHeader = 5
	MessageHeader_POINT           MessageHeader = 6
	MessageHeader_PRIVATE_KEY     MessageHeader = 7
	MessageHeader_SIGNATURE       MessageHeader = 8
	MessageHeader_COMMAND_OF_WORD MessageHeader = 9
	MessageHeader_TICKET          MessageHeader = 10
	MessageHeader_SIGNAL_OF_START MessageHeader = 11
	MessageHeader_COMMITMENT      MessageHeader = 12
	MessageHeader_CHALLENGE       MessageHeader = 13
	MessageHeader_RESPONSE        MessageHeader = 14
)

var MessageHeader_name = map[int32]string{
	0:  "ACCOUNT",
	1:  "BLOCK_HEADER",
	2:  "BLOCK_DATA",
	3:  "BLOCK",
	4:  "TRANSACTION",
	5:  "TIMESTAMP",
	6:  "POINT",
	7:  "PRIVATE_KEY",
	8:  "SIGNATURE",
	9:  "COMMAND_OF_WORD",
	10: "TICKET",
	11: "SIGNAL_OF_START",
	12: "COMMITMENT",
	13: "CHALLENGE",
	14: "RESPONSE",
}
var MessageHeader_value = map[string]int32{
	"ACCOUNT":         0,
	"BLOCK_HEADER":    1,
	"BLOCK_DATA":      2,
	"BLOCK":           3,
	"TRANSACTION":     4,
	"TIMESTAMP":       5,
	"POINT":           6,
	"PRIVATE_KEY":     7,
	"SIGNATURE":       8,
	"COMMAND_OF_WORD": 9,
	"TICKET":          10,
	"SIGNAL_OF_START": 11,
	"COMMITMENT":      12,
	"CHALLENGE":       13,
	"RESPONSE":        14,
}

func (x MessageHeader) String() string {
	return proto.EnumName(MessageHeader_name, int32(x))
}
func (MessageHeader) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_serializable_184465d9b1d7bb15, []int{0}
}

type Serializable struct {
	Header               MessageHeader `protobuf:"varint,1,opt,name=header,proto3,enum=network.MessageHeader" json:"header,omitempty"`
	Body                 []byte        `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Serializable) Reset()         { *m = Serializable{} }
func (m *Serializable) String() string { return proto.CompactTextString(m) }
func (*Serializable) ProtoMessage()    {}
func (*Serializable) Descriptor() ([]byte, []int) {
	return fileDescriptor_serializable_184465d9b1d7bb15, []int{0}
}
func (m *Serializable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Serializable.Unmarshal(m, b)
}
func (m *Serializable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Serializable.Marshal(b, m, deterministic)
}
func (dst *Serializable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Serializable.Merge(dst, src)
}
func (m *Serializable) XXX_Size() int {
	return xxx_messageInfo_Serializable.Size(m)
}
func (m *Serializable) XXX_DiscardUnknown() {
	xxx_messageInfo_Serializable.DiscardUnknown(m)
}

var xxx_messageInfo_Serializable proto.InternalMessageInfo

func (m *Serializable) GetHeader() MessageHeader {
	if m != nil {
		return m.Header
	}
	return MessageHeader_ACCOUNT
}

func (m *Serializable) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Serializable)(nil), "network.serializable")
	proto.RegisterEnum("network.MessageHeader", MessageHeader_name, MessageHeader_value)
}

func init() { proto.RegisterFile("serializable.proto", fileDescriptor_serializable_184465d9b1d7bb15) }

var fileDescriptor_serializable_184465d9b1d7bb15 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0x07, 0xf0, 0xaf, 0x7c, 0x50, 0x60, 0x28, 0x65, 0x32, 0x1e, 0xe4, 0x48, 0x3c, 0x11, 0x0f,
	0x98, 0xe8, 0x13, 0xac, 0xed, 0x0a, 0x0d, 0xed, 0x6e, 0xb3, 0x1d, 0x34, 0x9e, 0x9a, 0x12, 0x1a,
	0x25, 0xa2, 0x35, 0x85, 0xc4, 0xe8, 0x93, 0x7b, 0x34, 0x5b, 0x38, 0xe8, 0x6d, 0x77, 0xfe, 0xbf,
	0x99, 0x4c, 0x06, 0x68, 0x5f, 0xd6, 0xdb, 0x62, 0xb7, 0xfd, 0x2a, 0xd6, 0xbb, 0x72, 0xf6, 0x5e,
	0x57, 0x87, 0x8a, 0xba, 0x6f, 0xe5, 0xe1, 0xa3, 0xaa, 0x5f, 0x2e, 0x32, 0xf0, 0x7e, 0xc7, 0x74,
	0x05, 0xee, 0x73, 0x59, 0x6c, 0xca, 0x7a, 0xec, 0x4c, 0x9c, 0xa9, 0x7f, 0x7d, 0x3e, 0x3b, 0xc9,
	0xd9, 0x6b, 0xb9, 0xdf, 0x17, 0x4f, 0x65, 0x7e, 0x8c, 0xcd, 0x89, 0x11, 0x41, 0x7b, 0x5d, 0x6d,
	0x3e, 0xc7, 0xad, 0x89, 0x33, 0xf5, 0x4c, 0xf3, 0xbe, 0xfc, 0x76, 0xc0, 0xff, 0xcb, 0x69, 0x00,
	0x5d, 0x11, 0x04, 0x7a, 0xa5, 0x18, 0xff, 0x11, 0x82, 0x77, 0x1b, 0xeb, 0x60, 0x99, 0x2f, 0xa4,
	0x08, 0xa5, 0x41, 0x87, 0x7c, 0x80, 0x63, 0x25, 0x14, 0x2c, 0xb0, 0x45, 0x7d, 0xe8, 0x34, 0x7f,
	0xfc, 0x4f, 0x23, 0x18, 0xb0, 0x11, 0x2a, 0x13, 0x01, 0x47, 0x5a, 0x61, 0x9b, 0x86, 0xd0, 0xe7,
	0x28, 0x91, 0x19, 0x8b, 0x24, 0xc5, 0x8e, 0xa5, 0xa9, 0x8e, 0x14, 0xa3, 0x6b, 0x69, 0x6a, 0xa2,
	0x7b, 0xc1, 0x32, 0x5f, 0xca, 0x47, 0xec, 0x5a, 0x9a, 0x45, 0x73, 0x25, 0x78, 0x65, 0x24, 0xf6,
	0xe8, 0x0c, 0x46, 0x81, 0x4e, 0x12, 0xa1, 0xc2, 0x5c, 0xdf, 0xe5, 0x0f, 0xda, 0x84, 0xd8, 0x27,
	0x00, 0x97, 0xa3, 0x60, 0x29, 0x19, 0xc1, 0x82, 0xc6, 0xc7, 0x36, 0xcf, 0x58, 0x18, 0xc6, 0x81,
	0xdd, 0xcd, 0x76, 0x45, 0x9c, 0x48, 0xc5, 0xe8, 0xd9, 0xa1, 0xc1, 0x42, 0xc4, 0xb1, 0x54, 0x73,
	0x89, 0x43, 0xf2, 0xa0, 0x67, 0x64, 0x96, 0x6a, 0x95, 0x49, 0xf4, 0xd7, 0x6e, 0x73, 0xdf, 0x9b,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x14, 0x99, 0x58, 0x75, 0x01, 0x00, 0x00,
}
