// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction_types.proto

package network

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction struct {
	Version              int32      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Nonce                int64      `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ToAddress            []byte     `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount               []byte     `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	GasPrice             []byte     `protobuf:"bytes,5,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit             []byte     `protobuf:"bytes,6,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Timestamp            int64      `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PubKey               *Point     `protobuf:"bytes,8,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Sig                  *Signature `protobuf:"bytes,9,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_types_98f24a12ef0326d2, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Transaction) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetToAddress() []byte {
	if m != nil {
		return m.ToAddress
	}
	return nil
}

func (m *Transaction) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Transaction) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *Transaction) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetPubKey() *Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Transaction) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "network.transaction")
}

func init() {
	proto.RegisterFile("transaction_types.proto", fileDescriptor_transaction_types_98f24a12ef0326d2)
}

var fileDescriptor_transaction_types_98f24a12ef0326d2 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4d, 0x4a, 0xf4, 0x40,
	0x10, 0x86, 0xc9, 0xe4, 0x4b, 0x32, 0xa9, 0xf9, 0x70, 0x51, 0x88, 0x36, 0xfe, 0x40, 0x10, 0xc1,
	0xac, 0xb2, 0xd0, 0x13, 0xb8, 0xd6, 0x85, 0xe4, 0x02, 0xa1, 0x93, 0x69, 0x42, 0x33, 0xa6, 0xab,
	0xe9, 0xaa, 0x28, 0x39, 0x8b, 0x97, 0x95, 0x64, 0x7e, 0x9c, 0xe5, 0xf3, 0x3e, 0x6f, 0x41, 0x55,
	0xc1, 0xb5, 0x04, 0xed, 0x58, 0x77, 0x62, 0xc9, 0x35, 0x32, 0x79, 0xc3, 0x95, 0x0f, 0x24, 0x84,
	0x99, 0x33, 0xf2, 0x4d, 0x61, 0x77, 0x83, 0x5d, 0x98, 0xbc, 0xd0, 0xb9, 0x7c, 0xf8, 0x59, 0xc1,
	0xe6, 0x6c, 0x10, 0x15, 0x64, 0x5f, 0x26, 0xb0, 0x25, 0xa7, 0xa2, 0x22, 0x2a, 0x93, 0xfa, 0x88,
	0x78, 0x09, 0x89, 0x23, 0xd7, 0x19, 0xb5, 0x2a, 0xa2, 0x32, 0xae, 0xf7, 0x80, 0xf7, 0x00, 0x42,
	0x8d, 0xde, 0x6e, 0x83, 0x61, 0x56, 0x71, 0x11, 0x95, 0xff, 0xeb, 0x5c, 0xe8, 0x75, 0x1f, 0xe0,
	0x15, 0xa4, 0x7a, 0xa0, 0xd1, 0x89, 0xfa, 0xb7, 0xa8, 0x03, 0xe1, 0x2d, 0xe4, 0xbd, 0xe6, 0xc6,
	0x07, 0xdb, 0x19, 0x95, 0x2c, 0x6a, 0xdd, 0x6b, 0xfe, 0x98, 0xf9, 0x28, 0x3f, 0xed, 0x60, 0x45,
	0xa5, 0x27, 0xf9, 0x3e, 0x33, 0xde, 0x41, 0x2e, 0x76, 0x30, 0x2c, 0x7a, 0xf0, 0x2a, 0x5b, 0x56,
	0xf9, 0x0b, 0xf0, 0x09, 0x32, 0x3f, 0xb6, 0xcd, 0xce, 0x4c, 0x6a, 0x5d, 0x44, 0xe5, 0xe6, 0xf9,
	0xa2, 0x3a, 0x5c, 0x5f, 0x79, 0xb2, 0x4e, 0xea, 0xd4, 0x8f, 0xed, 0x9b, 0x99, 0xf0, 0x11, 0x62,
	0xb6, 0xbd, 0xca, 0x97, 0x12, 0x9e, 0x4a, 0x6c, 0x7b, 0xa7, 0x65, 0x0c, 0xa6, 0x9e, 0x75, 0x9b,
	0x2e, 0x4f, 0x7a, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x91, 0xc0, 0xbe, 0x91, 0x5c, 0x01, 0x00,
	0x00,
}
