// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account_types.proto

package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	PrvKey               *PrivateKey `protobuf:"bytes,1,opt,name=prv_key,json=prvKey,proto3" json:"prv_key,omitempty"`
	Address              []byte      `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Balance              []byte      `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	TxCount              int64       `protobuf:"varint,4,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_types_eed814fd39324531, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetPrvKey() *PrivateKey {
	if m != nil {
		return m.PrvKey
	}
	return nil
}

func (m *Account) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Account) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *Account) GetTxCount() int64 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func init() {
	proto.RegisterType((*Account)(nil), "account.account")
}

func init() { proto.RegisterFile("account_types.proto", fileDescriptor_account_types_eed814fd39324531) }

var fileDescriptor_account_types_eed814fd39324531 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0x89, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x87, 0x0a, 0x4a, 0x09, 0x25, 0x17, 0x55, 0x16, 0x94, 0xe4, 0x23, 0x4b, 0x2a, 0xb5, 0x33,
	0x72, 0xc1, 0xe4, 0x85, 0x74, 0xb9, 0xd8, 0x0b, 0x8a, 0xca, 0xe2, 0xb3, 0x53, 0x2b, 0x25, 0x18,
	0x15, 0x18, 0x35, 0xb8, 0x8d, 0x44, 0xf4, 0xa0, 0x52, 0x7a, 0x05, 0x45, 0x99, 0x65, 0x89, 0x25,
	0xa9, 0x20, 0xb9, 0x20, 0xb6, 0x82, 0xa2, 0x32, 0xef, 0xd4, 0x4a, 0x21, 0x09, 0x2e, 0xf6, 0xc4,
	0x94, 0x94, 0xa2, 0xd4, 0xe2, 0x62, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x18, 0x17, 0x24,
	0x93, 0x94, 0x98, 0x93, 0x98, 0x97, 0x9c, 0x2a, 0xc1, 0x0c, 0x91, 0x81, 0x72, 0x85, 0x24, 0xb9,
	0x38, 0x4a, 0x2a, 0xe2, 0xc1, 0x66, 0x4a, 0xb0, 0x28, 0x30, 0x6a, 0x30, 0x07, 0xb1, 0x97, 0x54,
	0x38, 0x83, 0xb8, 0x49, 0x6c, 0x60, 0x07, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x00, 0xbe,
	0xac, 0x7d, 0xc4, 0x00, 0x00, 0x00,
}
