// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type.proto

package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageHeader int32

const (
	MessageHeader_ACCOUNT          MessageHeader = 0
	MessageHeader_BLOCK_HEADER     MessageHeader = 1
	MessageHeader_BLOCK_DATA       MessageHeader = 2
	MessageHeader_BLOCK            MessageHeader = 3
	MessageHeader_TRANSACTION      MessageHeader = 4
	MessageHeader_TIMESTAMP        MessageHeader = 5
	MessageHeader_POINT            MessageHeader = 6
	MessageHeader_PRIVATE_KEY      MessageHeader = 7
	MessageHeader_SIGNATURE        MessageHeader = 8
	MessageHeader_WORD             MessageHeader = 9
	MessageHeader_TICKET           MessageHeader = 10
	MessageHeader_COMMITMENT       MessageHeader = 11
	MessageHeader_CHALLENGE        MessageHeader = 12
	MessageHeader_RESPONSE         MessageHeader = 13
	MessageHeader_TRANSACTION_DATA MessageHeader = 14
)

var MessageHeader_name = map[int32]string{
	0:  "ACCOUNT",
	1:  "BLOCK_HEADER",
	2:  "BLOCK_DATA",
	3:  "BLOCK",
	4:  "TRANSACTION",
	5:  "TIMESTAMP",
	6:  "POINT",
	7:  "PRIVATE_KEY",
	8:  "SIGNATURE",
	9:  "WORD",
	10: "TICKET",
	11: "COMMITMENT",
	12: "CHALLENGE",
	13: "RESPONSE",
	14: "TRANSACTION_DATA",
}
var MessageHeader_value = map[string]int32{
	"ACCOUNT":          0,
	"BLOCK_HEADER":     1,
	"BLOCK_DATA":       2,
	"BLOCK":            3,
	"TRANSACTION":      4,
	"TIMESTAMP":        5,
	"POINT":            6,
	"PRIVATE_KEY":      7,
	"SIGNATURE":        8,
	"WORD":             9,
	"TICKET":           10,
	"COMMITMENT":       11,
	"CHALLENGE":        12,
	"RESPONSE":         13,
	"TRANSACTION_DATA": 14,
}

func (x MessageHeader) String() string {
	return proto.EnumName(MessageHeader_name, int32(x))
}
func (MessageHeader) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{0}
}

type Serializable struct {
	Header               MessageHeader `protobuf:"varint,1,opt,name=header,proto3,enum=common.MessageHeader" json:"header,omitempty"`
	Body                 []byte        `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Address              string        `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PubKey               *Point        `protobuf:"bytes,4,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Sig                  *Signature    `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Serializable) Reset()         { *m = Serializable{} }
func (m *Serializable) String() string { return proto.CompactTextString(m) }
func (*Serializable) ProtoMessage()    {}
func (*Serializable) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{0}
}
func (m *Serializable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Serializable.Unmarshal(m, b)
}
func (m *Serializable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Serializable.Marshal(b, m, deterministic)
}
func (dst *Serializable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Serializable.Merge(dst, src)
}
func (m *Serializable) XXX_Size() int {
	return xxx_messageInfo_Serializable.Size(m)
}
func (m *Serializable) XXX_DiscardUnknown() {
	xxx_messageInfo_Serializable.DiscardUnknown(m)
}

var xxx_messageInfo_Serializable proto.InternalMessageInfo

func (m *Serializable) GetHeader() MessageHeader {
	if m != nil {
		return m.Header
	}
	return MessageHeader_ACCOUNT
}

func (m *Serializable) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Serializable) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Serializable) GetPubKey() *Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Serializable) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Point struct {
	X                    []byte   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    []byte   `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{1}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *Point) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

type PrivateKey struct {
	Prv                  []byte   `protobuf:"bytes,1,opt,name=prv,proto3" json:"prv,omitempty"`
	PubKey               *Point   `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateKey) Reset()         { *m = PrivateKey{} }
func (m *PrivateKey) String() string { return proto.CompactTextString(m) }
func (*PrivateKey) ProtoMessage()    {}
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{2}
}
func (m *PrivateKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKey.Unmarshal(m, b)
}
func (m *PrivateKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKey.Marshal(b, m, deterministic)
}
func (dst *PrivateKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKey.Merge(dst, src)
}
func (m *PrivateKey) XXX_Size() int {
	return xxx_messageInfo_PrivateKey.Size(m)
}
func (m *PrivateKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKey.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKey proto.InternalMessageInfo

func (m *PrivateKey) GetPrv() []byte {
	if m != nil {
		return m.Prv
	}
	return nil
}

func (m *PrivateKey) GetPubKey() *Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type Signature struct {
	R                    []byte   `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	S                    []byte   `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{3}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (dst *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(dst, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *Signature) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

type Word struct {
	Msg                  []byte   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Word) Reset()         { *m = Word{} }
func (m *Word) String() string { return proto.CompactTextString(m) }
func (*Word) ProtoMessage()    {}
func (*Word) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{4}
}
func (m *Word) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Word.Unmarshal(m, b)
}
func (m *Word) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Word.Marshal(b, m, deterministic)
}
func (dst *Word) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Word.Merge(dst, src)
}
func (m *Word) XXX_Size() int {
	return xxx_messageInfo_Word.Size(m)
}
func (m *Word) XXX_DiscardUnknown() {
	xxx_messageInfo_Word.DiscardUnknown(m)
}

var xxx_messageInfo_Word proto.InternalMessageInfo

func (m *Word) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Ticket struct {
	SigOfWord            *Signature `protobuf:"bytes,1,opt,name=sig_of_word,json=sigOfWord,proto3" json:"sig_of_word,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{5}
}
func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (dst *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(dst, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetSigOfWord() *Signature {
	if m != nil {
		return m.SigOfWord
	}
	return nil
}

type Commitment struct {
	Q                    *Point   `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commitment) Reset()         { *m = Commitment{} }
func (m *Commitment) String() string { return proto.CompactTextString(m) }
func (*Commitment) ProtoMessage()    {}
func (*Commitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{6}
}
func (m *Commitment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commitment.Unmarshal(m, b)
}
func (m *Commitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commitment.Marshal(b, m, deterministic)
}
func (dst *Commitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commitment.Merge(dst, src)
}
func (m *Commitment) XXX_Size() int {
	return xxx_messageInfo_Commitment.Size(m)
}
func (m *Commitment) XXX_DiscardUnknown() {
	xxx_messageInfo_Commitment.DiscardUnknown(m)
}

var xxx_messageInfo_Commitment proto.InternalMessageInfo

func (m *Commitment) GetQ() *Point {
	if m != nil {
		return m.Q
	}
	return nil
}

type Challenge struct {
	GroupPubKey          *Point   `protobuf:"bytes,1,opt,name=group_pub_key,json=groupPubKey,proto3" json:"group_pub_key,omitempty"`
	GroupQ               *Point   `protobuf:"bytes,2,opt,name=group_q,json=groupQ,proto3" json:"group_q,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	R                    []byte   `protobuf:"bytes,4,opt,name=r,proto3" json:"r,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Challenge) Reset()         { *m = Challenge{} }
func (m *Challenge) String() string { return proto.CompactTextString(m) }
func (*Challenge) ProtoMessage()    {}
func (*Challenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{7}
}
func (m *Challenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Challenge.Unmarshal(m, b)
}
func (m *Challenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Challenge.Marshal(b, m, deterministic)
}
func (dst *Challenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Challenge.Merge(dst, src)
}
func (m *Challenge) XXX_Size() int {
	return xxx_messageInfo_Challenge.Size(m)
}
func (m *Challenge) XXX_DiscardUnknown() {
	xxx_messageInfo_Challenge.DiscardUnknown(m)
}

var xxx_messageInfo_Challenge proto.InternalMessageInfo

func (m *Challenge) GetGroupPubKey() *Point {
	if m != nil {
		return m.GroupPubKey
	}
	return nil
}

func (m *Challenge) GetGroupQ() *Point {
	if m != nil {
		return m.GroupQ
	}
	return nil
}

func (m *Challenge) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Challenge) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

type Response struct {
	S                    []byte   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{8}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

type BlockHeader struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PreviousHash         []byte   `protobuf:"bytes,2,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	GasLimit             []byte   `protobuf:"bytes,3,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed              []byte   `protobuf:"bytes,4,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Height               []byte   `protobuf:"bytes,5,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MerkleRoot           []byte   `protobuf:"bytes,7,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	TxHashes             [][]byte `protobuf:"bytes,8,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	LeaderPubKey         *Point   `protobuf:"bytes,9,opt,name=leader_pub_key,json=leaderPubKey,proto3" json:"leader_pub_key,omitempty"`
	MinorPubKeys         []*Point `protobuf:"bytes,10,rep,name=minor_pub_keys,json=minorPubKeys,proto3" json:"minor_pub_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{9}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockHeader) GetPreviousHash() []byte {
	if m != nil {
		return m.PreviousHash
	}
	return nil
}

func (m *BlockHeader) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *BlockHeader) GetGasUsed() []byte {
	if m != nil {
		return m.GasUsed
	}
	return nil
}

func (m *BlockHeader) GetHeight() []byte {
	if m != nil {
		return m.Height
	}
	return nil
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *BlockHeader) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func (m *BlockHeader) GetLeaderPubKey() *Point {
	if m != nil {
		return m.LeaderPubKey
	}
	return nil
}

func (m *BlockHeader) GetMinorPubKeys() []*Point {
	if m != nil {
		return m.MinorPubKeys
	}
	return nil
}

type BlockData struct {
	TxCount              int32          `protobuf:"varint,1,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	TxList               []*Transaction `protobuf:"bytes,2,rep,name=tx_list,json=txList,proto3" json:"tx_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockData) Reset()         { *m = BlockData{} }
func (m *BlockData) String() string { return proto.CompactTextString(m) }
func (*BlockData) ProtoMessage()    {}
func (*BlockData) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{10}
}
func (m *BlockData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockData.Unmarshal(m, b)
}
func (m *BlockData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockData.Marshal(b, m, deterministic)
}
func (dst *BlockData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockData.Merge(dst, src)
}
func (m *BlockData) XXX_Size() int {
	return xxx_messageInfo_BlockData.Size(m)
}
func (m *BlockData) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockData.DiscardUnknown(m)
}

var xxx_messageInfo_BlockData proto.InternalMessageInfo

func (m *BlockData) GetTxCount() int32 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func (m *BlockData) GetTxList() []*Transaction {
	if m != nil {
		return m.TxList
	}
	return nil
}

type Block struct {
	Header               *BlockHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Data                 *BlockData   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	MultiSig             *Signature   `protobuf:"bytes,4,opt,name=multi_sig,json=multiSig,proto3" json:"multi_sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{11}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetData() *BlockData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetMultiSig() *Signature {
	if m != nil {
		return m.MultiSig
	}
	return nil
}

type TransactionData struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Nonce                int64    `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ToAddress            []byte   `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount               []byte   `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	GasPrice             []byte   `protobuf:"bytes,5,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit             []byte   `protobuf:"bytes,6,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PubKey               *Point   `protobuf:"bytes,8,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionData) Reset()         { *m = TransactionData{} }
func (m *TransactionData) String() string { return proto.CompactTextString(m) }
func (*TransactionData) ProtoMessage()    {}
func (*TransactionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{12}
}
func (m *TransactionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionData.Unmarshal(m, b)
}
func (m *TransactionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionData.Marshal(b, m, deterministic)
}
func (dst *TransactionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionData.Merge(dst, src)
}
func (m *TransactionData) XXX_Size() int {
	return xxx_messageInfo_TransactionData.Size(m)
}
func (m *TransactionData) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionData.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionData proto.InternalMessageInfo

func (m *TransactionData) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TransactionData) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TransactionData) GetToAddress() []byte {
	if m != nil {
		return m.ToAddress
	}
	return nil
}

func (m *TransactionData) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *TransactionData) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *TransactionData) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *TransactionData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TransactionData) GetPubKey() *Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type Transaction struct {
	Data                 *TransactionData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Sig                  *Signature       `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{13}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetData() *TransactionData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Account struct {
	PrvKey               *PrivateKey `protobuf:"bytes,1,opt,name=prv_key,json=prvKey,proto3" json:"prv_key,omitempty"`
	Address              []byte      `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Balance              []byte      `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	TxCount              int64       `protobuf:"varint,4,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_039f207e76b81974, []int{14}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetPrvKey() *PrivateKey {
	if m != nil {
		return m.PrvKey
	}
	return nil
}

func (m *Account) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Account) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *Account) GetTxCount() int64 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func init() {
	proto.RegisterType((*Serializable)(nil), "common.serializable")
	proto.RegisterType((*Point)(nil), "common.point")
	proto.RegisterType((*PrivateKey)(nil), "common.private_key")
	proto.RegisterType((*Signature)(nil), "common.signature")
	proto.RegisterType((*Word)(nil), "common.word")
	proto.RegisterType((*Ticket)(nil), "common.ticket")
	proto.RegisterType((*Commitment)(nil), "common.commitment")
	proto.RegisterType((*Challenge)(nil), "common.challenge")
	proto.RegisterType((*Response)(nil), "common.response")
	proto.RegisterType((*BlockHeader)(nil), "common.block_header")
	proto.RegisterType((*BlockData)(nil), "common.block_data")
	proto.RegisterType((*Block)(nil), "common.block")
	proto.RegisterType((*TransactionData)(nil), "common.transaction_data")
	proto.RegisterType((*Transaction)(nil), "common.transaction")
	proto.RegisterType((*Account)(nil), "common.account")
	proto.RegisterEnum("common.MessageHeader", MessageHeader_name, MessageHeader_value)
}

func init() { proto.RegisterFile("type.proto", fileDescriptor_type_039f207e76b81974) }

var fileDescriptor_type_039f207e76b81974 = []byte{
	// 995 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x4d, 0x6f, 0xeb, 0x44,
	0x14, 0xc5, 0xf9, 0x70, 0xe2, 0x1b, 0x37, 0x98, 0xa1, 0xaa, 0x8c, 0x1e, 0x88, 0xc8, 0x95, 0x4a,
	0x41, 0x55, 0xa5, 0xd7, 0x2e, 0x59, 0x99, 0xd4, 0x6a, 0xa3, 0xb6, 0x49, 0x70, 0x5c, 0x9e, 0x58,
	0x99, 0x49, 0x32, 0xcf, 0x19, 0xd5, 0xf6, 0xb8, 0x9e, 0x49, 0x48, 0xf9, 0x01, 0x6f, 0xc7, 0x0f,
	0xe2, 0xf7, 0xb0, 0x67, 0xcf, 0x0e, 0xcd, 0xd8, 0x0e, 0x6e, 0xd5, 0x76, 0xe7, 0x3b, 0x73, 0xee,
	0xdc, 0x33, 0xe7, 0x1e, 0xdf, 0x01, 0x10, 0x8f, 0x19, 0x39, 0xcd, 0x72, 0x26, 0x18, 0xd2, 0x17,
	0x2c, 0x49, 0x58, 0xea, 0xfc, 0xa5, 0x81, 0xc9, 0x49, 0x4e, 0x71, 0x4c, 0xff, 0xc0, 0xf3, 0x98,
	0xa0, 0x53, 0xd0, 0x57, 0x04, 0x2f, 0x49, 0x6e, 0x6b, 0x03, 0xed, 0xb8, 0x7f, 0x76, 0x70, 0x5a,
	0x20, 0x4f, 0x13, 0xc2, 0x39, 0x8e, 0x48, 0x58, 0xec, 0xfa, 0x25, 0x0a, 0x21, 0x68, 0xcd, 0xd9,
	0xf2, 0xd1, 0x6e, 0x0c, 0xb4, 0x63, 0xd3, 0x57, 0xdf, 0xc8, 0x86, 0x0e, 0x5e, 0x2e, 0x73, 0xc2,
	0xb9, 0xdd, 0x1c, 0x68, 0xc7, 0x86, 0x5f, 0x85, 0xe8, 0x08, 0x3a, 0xd9, 0x7a, 0x1e, 0xde, 0x93,
	0x47, 0xbb, 0x35, 0xd0, 0x8e, 0x7b, 0x67, 0x7b, 0xd5, 0xf1, 0x19, 0xa3, 0xa9, 0xf0, 0xf5, 0x6c,
	0x3d, 0xbf, 0x26, 0x8f, 0xe8, 0x10, 0x9a, 0x9c, 0x46, 0x76, 0x5b, 0x61, 0xbe, 0xa8, 0x30, 0x9c,
	0x46, 0x29, 0x16, 0xeb, 0x9c, 0xf8, 0x72, 0xd7, 0x39, 0x84, 0xb6, 0xca, 0x42, 0x26, 0x68, 0x5b,
	0x45, 0xd7, 0xf4, 0xb5, 0xad, 0x8c, 0x2a, 0x3a, 0xda, 0xa3, 0x73, 0x09, 0xbd, 0x2c, 0xa7, 0x1b,
	0x2c, 0x88, 0xac, 0x8a, 0x2c, 0x68, 0x66, 0xf9, 0xa6, 0x04, 0xcb, 0xcf, 0x3a, 0xa5, 0xc6, 0x1b,
	0x94, 0x9c, 0xef, 0xc0, 0xd8, 0xd5, 0x97, 0x35, 0xf2, 0xaa, 0x62, 0x2e, 0x23, 0x5e, 0x55, 0xe4,
	0x8e, 0x0d, 0xad, 0xdf, 0x59, 0xbe, 0x94, 0xa5, 0x12, 0x1e, 0x55, 0xa5, 0x12, 0x1e, 0x39, 0x3f,
	0x82, 0x2e, 0xe8, 0xe2, 0x9e, 0x08, 0xf4, 0x1e, 0x7a, 0x9c, 0x46, 0x21, 0xfb, 0x18, 0x4a, 0xa8,
	0xc2, 0xbc, 0x78, 0x4f, 0x59, 0x72, 0xf2, 0xf1, 0x03, 0xcb, 0x97, 0xce, 0xf7, 0x00, 0x72, 0x9b,
	0x8a, 0x84, 0xa4, 0x02, 0xbd, 0x03, 0xed, 0xa1, 0x4c, 0x7b, 0xc6, 0x57, 0x7b, 0x70, 0x3e, 0x69,
	0x60, 0x2c, 0x56, 0x38, 0x8e, 0x49, 0x1a, 0x11, 0xf4, 0x1e, 0xf6, 0xa2, 0x9c, 0xad, 0xb3, 0xb0,
	0xba, 0xe6, 0x8b, 0x69, 0x3d, 0x85, 0x99, 0x16, 0xf2, 0x1f, 0x41, 0xa7, 0x48, 0x79, 0x78, 0x45,
	0x13, 0xb5, 0xfb, 0x73, 0x75, 0xc5, 0xe6, 0xee, 0x8a, 0x85, 0x30, 0xad, 0x52, 0x18, 0xc7, 0x86,
	0x6e, 0x4e, 0x78, 0xc6, 0x52, 0x4e, 0x0a, 0x91, 0xb4, 0x4a, 0xa4, 0xbf, 0x1b, 0x60, 0xce, 0x63,
	0xb6, 0xb8, 0x2f, 0xfd, 0x24, 0x3d, 0xb3, 0x21, 0x39, 0xa7, 0x2c, 0x55, 0xa0, 0xb6, 0x5f, 0x85,
	0xe8, 0x10, 0xf6, 0xb2, 0x9c, 0x6c, 0x28, 0x5b, 0xf3, 0x70, 0x85, 0xf9, 0xaa, 0x54, 0xda, 0xac,
	0x16, 0xaf, 0x30, 0x5f, 0xa1, 0x77, 0x60, 0x44, 0x98, 0x87, 0x31, 0x4d, 0xa8, 0x28, 0xf9, 0x74,
	0x23, 0xcc, 0x6f, 0x64, 0x8c, 0xbe, 0x02, 0xf9, 0x1d, 0xae, 0x39, 0x59, 0x96, 0xdc, 0x3a, 0x11,
	0xe6, 0x77, 0x9c, 0x2c, 0xd1, 0x81, 0xb4, 0x3b, 0x8d, 0x56, 0x42, 0x79, 0xcd, 0xf4, 0xcb, 0x08,
	0x7d, 0x0d, 0x86, 0xa0, 0x09, 0xe1, 0x02, 0x27, 0x99, 0xad, 0x0f, 0xb4, 0xe3, 0xa6, 0xff, 0xff,
	0x02, 0xfa, 0x16, 0x7a, 0x09, 0xc9, 0xef, 0x63, 0x12, 0xe6, 0x8c, 0x09, 0xbb, 0xa3, 0x52, 0xa1,
	0x58, 0xf2, 0x19, 0x93, 0xed, 0x31, 0xc4, 0x56, 0xb1, 0x25, 0xdc, 0xee, 0x0e, 0x9a, 0x92, 0x8e,
	0xd8, 0x5e, 0xa9, 0x18, 0x9d, 0x43, 0x3f, 0x56, 0x97, 0xde, 0x75, 0xc4, 0x78, 0x49, 0x64, 0xb3,
	0x00, 0x95, 0x2d, 0x39, 0x87, 0x7e, 0x42, 0x53, 0xb6, 0xcb, 0xe1, 0x36, 0x0c, 0x9a, 0x2f, 0x24,
	0x29, 0x50, 0x91, 0xc3, 0x9d, 0x3b, 0x80, 0x42, 0xe4, 0x25, 0x16, 0x58, 0xca, 0x20, 0xb6, 0xe1,
	0x82, 0xad, 0x53, 0x51, 0x69, 0x2c, 0xb6, 0x43, 0x19, 0xa2, 0x13, 0xe8, 0x88, 0x6d, 0x18, 0x53,
	0x2e, 0xec, 0x86, 0x3a, 0xf6, 0xcb, 0xea, 0x58, 0x91, 0xe3, 0x94, 0xe3, 0x85, 0xa0, 0x2c, 0xf5,
	0x75, 0xb1, 0xbd, 0xa1, 0x5c, 0x38, 0x7f, 0x6a, 0xd0, 0x56, 0xe7, 0xa2, 0x93, 0xdd, 0xb4, 0x28,
	0x7c, 0xb2, 0x5f, 0xa5, 0xd5, 0x7b, 0xbb, 0x9b, 0x15, 0x47, 0xd0, 0x92, 0x44, 0x54, 0x7f, 0x7a,
	0x67, 0xe8, 0x29, 0x56, 0xee, 0xf8, 0x6a, 0x1f, 0x9d, 0x82, 0x91, 0xac, 0x63, 0x41, 0x43, 0x39,
	0x03, 0x5a, 0xaf, 0xfd, 0x1b, 0x5d, 0x85, 0x99, 0xd1, 0xc8, 0xf9, 0x57, 0x03, 0xab, 0xc6, 0xb3,
	0xb8, 0xed, 0xeb, 0x86, 0xda, 0x87, 0x76, 0xca, 0xd2, 0x05, 0x51, 0x9c, 0x9b, 0x7e, 0x11, 0xa0,
	0x6f, 0x00, 0x04, 0x0b, 0xeb, 0x73, 0xcb, 0xf4, 0x0d, 0xc1, 0xdc, 0x72, 0x72, 0x1d, 0x80, 0x8e,
	0x13, 0x25, 0x5d, 0xe1, 0xa0, 0x32, 0xaa, 0x8c, 0x97, 0xe5, 0x74, 0x41, 0x4a, 0x0f, 0x49, 0xb3,
	0x4d, 0x65, 0xfc, 0xd4, 0x95, 0xfa, 0x33, 0x57, 0x3e, 0xb1, 0x58, 0xe7, 0xb9, 0xc5, 0x6a, 0x63,
	0xa9, 0xfb, 0xd6, 0x58, 0xfa, 0x0d, 0x7a, 0xb5, 0xab, 0xa3, 0x93, 0x52, 0xe2, 0xe2, 0x1f, 0xb7,
	0x5f, 0xe8, 0x62, 0x5d, 0xe8, 0x72, 0xcc, 0x36, 0xde, 0x1c, 0xb3, 0x9f, 0x34, 0xe8, 0xe0, 0xc5,
	0xa2, 0xf2, 0x49, 0x96, 0x6f, 0x6a, 0x53, 0x64, 0xe7, 0x93, 0xda, 0x90, 0xf5, 0xf5, 0x2c, 0xdf,
	0x48, 0xcf, 0xd6, 0xde, 0x81, 0xe2, 0x9f, 0xdd, 0xbd, 0x03, 0x36, 0x74, 0xe6, 0x38, 0xc6, 0xb2,
	0x09, 0x85, 0xd2, 0x55, 0xf8, 0xc4, 0xa4, 0x2d, 0x25, 0x4a, 0x65, 0xd2, 0x1f, 0xfe, 0xd1, 0xa0,
	0xff, 0xf4, 0x15, 0x42, 0x3d, 0xe8, 0xb8, 0xc3, 0xe1, 0xe4, 0x6e, 0x1c, 0x58, 0x9f, 0x21, 0x0b,
	0xcc, 0x9f, 0x6e, 0x26, 0xc3, 0xeb, 0xf0, 0xca, 0x73, 0x2f, 0x3c, 0xdf, 0xd2, 0x50, 0x1f, 0xa0,
	0x58, 0xb9, 0x70, 0x03, 0xd7, 0x6a, 0x20, 0x03, 0xda, 0x2a, 0xb6, 0x9a, 0xe8, 0x73, 0xe8, 0x05,
	0xbe, 0x3b, 0x9e, 0xb9, 0xc3, 0x60, 0x34, 0x19, 0x5b, 0x2d, 0xb4, 0x07, 0x46, 0x30, 0xba, 0xf5,
	0x66, 0x81, 0x7b, 0x3b, 0xb5, 0xda, 0x12, 0x3a, 0x9d, 0x8c, 0xc6, 0x81, 0xa5, 0x4b, 0xe8, 0xd4,
	0x1f, 0xfd, 0xe2, 0x06, 0x5e, 0x78, 0xed, 0xfd, 0x6a, 0x75, 0x24, 0x74, 0x36, 0xba, 0x1c, 0xbb,
	0xc1, 0x9d, 0xef, 0x59, 0x5d, 0xd4, 0x85, 0xd6, 0x87, 0x89, 0x7f, 0x61, 0x19, 0x08, 0x40, 0x0f,
	0x46, 0xc3, 0x6b, 0x2f, 0xb0, 0x40, 0xd6, 0x1e, 0x4e, 0x6e, 0x6f, 0x47, 0xc1, 0xad, 0x37, 0x0e,
	0xac, 0x9e, 0x4c, 0x1a, 0x5e, 0xb9, 0x37, 0x37, 0xde, 0xf8, 0xd2, 0xb3, 0x4c, 0x64, 0x42, 0xd7,
	0xf7, 0x66, 0xd3, 0xc9, 0x78, 0xe6, 0x59, 0x7b, 0x68, 0x1f, 0xac, 0x1a, 0x9b, 0x82, 0x6e, 0x7f,
	0xae, 0xab, 0xb7, 0xfa, 0xfc, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x63, 0x2d, 0xe3, 0xde, 0xb9,
	0x07, 0x00, 0x00,
}
