// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consensus.proto

package bean

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Setup struct {
	Msg                  []byte     `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	PubKey               *Point     `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Sig                  *Signature `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Setup) Reset()         { *m = Setup{} }
func (m *Setup) String() string { return proto.CompactTextString(m) }
func (*Setup) ProtoMessage()    {}
func (*Setup) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_6ca9906e70f08143, []int{0}
}
func (m *Setup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Setup.Unmarshal(m, b)
}
func (m *Setup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Setup.Marshal(b, m, deterministic)
}
func (dst *Setup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Setup.Merge(dst, src)
}
func (m *Setup) XXX_Size() int {
	return xxx_messageInfo_Setup.Size(m)
}
func (m *Setup) XXX_DiscardUnknown() {
	xxx_messageInfo_Setup.DiscardUnknown(m)
}

var xxx_messageInfo_Setup proto.InternalMessageInfo

func (m *Setup) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Setup) GetPubKey() *Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Setup) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Commitment struct {
	PubKey               *Point   `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Q                    *Point   `protobuf:"bytes,2,opt,name=q,proto3" json:"q,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commitment) Reset()         { *m = Commitment{} }
func (m *Commitment) String() string { return proto.CompactTextString(m) }
func (*Commitment) ProtoMessage()    {}
func (*Commitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_6ca9906e70f08143, []int{1}
}
func (m *Commitment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commitment.Unmarshal(m, b)
}
func (m *Commitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commitment.Marshal(b, m, deterministic)
}
func (dst *Commitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commitment.Merge(dst, src)
}
func (m *Commitment) XXX_Size() int {
	return xxx_messageInfo_Commitment.Size(m)
}
func (m *Commitment) XXX_DiscardUnknown() {
	xxx_messageInfo_Commitment.DiscardUnknown(m)
}

var xxx_messageInfo_Commitment proto.InternalMessageInfo

func (m *Commitment) GetPubKey() *Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Commitment) GetQ() *Point {
	if m != nil {
		return m.Q
	}
	return nil
}

type Challenge struct {
	SigmaPubKey          *Point   `protobuf:"bytes,1,opt,name=sigma_pub_key,json=sigmaPubKey,proto3" json:"sigma_pub_key,omitempty"`
	SigmaQ               *Point   `protobuf:"bytes,2,opt,name=sigma_q,json=sigmaQ,proto3" json:"sigma_q,omitempty"`
	R                    []byte   `protobuf:"bytes,3,opt,name=r,proto3" json:"r,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Challenge) Reset()         { *m = Challenge{} }
func (m *Challenge) String() string { return proto.CompactTextString(m) }
func (*Challenge) ProtoMessage()    {}
func (*Challenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_6ca9906e70f08143, []int{2}
}
func (m *Challenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Challenge.Unmarshal(m, b)
}
func (m *Challenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Challenge.Marshal(b, m, deterministic)
}
func (dst *Challenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Challenge.Merge(dst, src)
}
func (m *Challenge) XXX_Size() int {
	return xxx_messageInfo_Challenge.Size(m)
}
func (m *Challenge) XXX_DiscardUnknown() {
	xxx_messageInfo_Challenge.DiscardUnknown(m)
}

var xxx_messageInfo_Challenge proto.InternalMessageInfo

func (m *Challenge) GetSigmaPubKey() *Point {
	if m != nil {
		return m.SigmaPubKey
	}
	return nil
}

func (m *Challenge) GetSigmaQ() *Point {
	if m != nil {
		return m.SigmaQ
	}
	return nil
}

func (m *Challenge) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

type Response struct {
	PubKey               *Point   `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	S                    []byte   `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_6ca9906e70f08143, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPubKey() *Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Response) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func init() {
	proto.RegisterType((*Setup)(nil), "bean.setup")
	proto.RegisterType((*Commitment)(nil), "bean.commitment")
	proto.RegisterType((*Challenge)(nil), "bean.challenge")
	proto.RegisterType((*Response)(nil), "bean.response")
}

func init() { proto.RegisterFile("consensus.proto", fileDescriptor_consensus_6ca9906e70f08143) }

var fileDescriptor_consensus_6ca9906e70f08143 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcf, 0x4e, 0xf3, 0x30,
	0x10, 0xc4, 0xb5, 0x5f, 0x3e, 0x52, 0xba, 0x09, 0x2a, 0xf2, 0x29, 0x70, 0x2a, 0x51, 0x0f, 0x3d,
	0x05, 0x09, 0xee, 0xbc, 0x00, 0x42, 0x82, 0xbc, 0x40, 0x15, 0x47, 0x2b, 0x63, 0xb5, 0xfe, 0x53,
	0xaf, 0x7d, 0xc8, 0xdb, 0xa3, 0x38, 0x17, 0x0e, 0x05, 0x71, 0xb3, 0x3c, 0x33, 0xbf, 0xdd, 0x1d,
	0xdc, 0x8c, 0xce, 0x32, 0x59, 0x4e, 0xdc, 0xf9, 0xe0, 0xa2, 0x13, 0xff, 0x25, 0x0d, 0xf6, 0x7e,
	0x7d, 0xa4, 0x69, 0xf9, 0x68, 0x25, 0x5e, 0x31, 0xc5, 0xe4, 0xc5, 0x2d, 0x16, 0x86, 0x55, 0x03,
	0x5b, 0xd8, 0xd7, 0xfd, 0xfc, 0x14, 0x3b, 0x5c, 0xf9, 0x24, 0x0f, 0x47, 0x9a, 0x9a, 0x7f, 0x5b,
	0xd8, 0x57, 0x4f, 0x55, 0x37, 0xa7, 0x3b, 0xef, 0xb4, 0x8d, 0x7d, 0xe9, 0x93, 0x7c, 0xa5, 0x49,
	0x3c, 0x60, 0xc1, 0x5a, 0x35, 0x45, 0x76, 0x6c, 0x16, 0x07, 0x6b, 0x65, 0x87, 0x98, 0x02, 0xf5,
	0xb3, 0xd6, 0xbe, 0x21, 0x8e, 0xce, 0x18, 0x1d, 0x0d, 0xd9, 0xf8, 0x1d, 0x0b, 0x3f, 0x63, 0xef,
	0x10, 0xce, 0x97, 0xc6, 0xc2, 0xb9, 0xf5, 0xb8, 0x1e, 0x3f, 0x87, 0xd3, 0x89, 0xac, 0x22, 0xf1,
	0x88, 0x37, 0xac, 0x95, 0x19, 0x0e, 0xbf, 0x30, 0xab, 0xec, 0x78, 0x5f, 0xc0, 0x3b, 0x5c, 0x2d,
	0x81, 0x8b, 0xf8, 0x32, 0x6b, 0x1f, 0xa2, 0x46, 0x08, 0xf9, 0xa6, 0xba, 0x87, 0xd0, 0xbe, 0xe0,
	0x75, 0x20, 0xf6, 0x73, 0x97, 0x7f, 0x5c, 0xbf, 0x46, 0xe0, 0xcc, 0xaf, 0x7b, 0x60, 0x59, 0xe6,
	0xae, 0x9f, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x5b, 0x32, 0x74, 0x8f, 0x01, 0x00, 0x00,
}
