// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package bean

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockHeader struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PreviousHash         []byte   `protobuf:"bytes,2,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	GasLimit             []byte   `protobuf:"bytes,3,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed              []byte   `protobuf:"bytes,4,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Height               []byte   `protobuf:"bytes,5,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MerkleRoot           []byte   `protobuf:"bytes,7,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	TxHashes             [][]byte `protobuf:"bytes,8,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	LeaderPubKey         *Point   `protobuf:"bytes,9,opt,name=leader_pub_key,json=leaderPubKey,proto3" json:"leader_pub_key,omitempty"`
	MinorPubKeys         []*Point `protobuf:"bytes,10,rep,name=minor_pub_keys,json=minorPubKeys,proto3" json:"minor_pub_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_2750a5e799b6b8ce, []int{0}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockHeader) GetPreviousHash() []byte {
	if m != nil {
		return m.PreviousHash
	}
	return nil
}

func (m *BlockHeader) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *BlockHeader) GetGasUsed() []byte {
	if m != nil {
		return m.GasUsed
	}
	return nil
}

func (m *BlockHeader) GetHeight() []byte {
	if m != nil {
		return m.Height
	}
	return nil
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *BlockHeader) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func (m *BlockHeader) GetLeaderPubKey() *Point {
	if m != nil {
		return m.LeaderPubKey
	}
	return nil
}

func (m *BlockHeader) GetMinorPubKeys() []*Point {
	if m != nil {
		return m.MinorPubKeys
	}
	return nil
}

type BlockData struct {
	TxCount              int32          `protobuf:"varint,1,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	TxList               []*Transaction `protobuf:"bytes,2,rep,name=tx_list,json=txList,proto3" json:"tx_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockData) Reset()         { *m = BlockData{} }
func (m *BlockData) String() string { return proto.CompactTextString(m) }
func (*BlockData) ProtoMessage()    {}
func (*BlockData) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_2750a5e799b6b8ce, []int{1}
}
func (m *BlockData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockData.Unmarshal(m, b)
}
func (m *BlockData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockData.Marshal(b, m, deterministic)
}
func (dst *BlockData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockData.Merge(dst, src)
}
func (m *BlockData) XXX_Size() int {
	return xxx_messageInfo_BlockData.Size(m)
}
func (m *BlockData) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockData.DiscardUnknown(m)
}

var xxx_messageInfo_BlockData proto.InternalMessageInfo

func (m *BlockData) GetTxCount() int32 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func (m *BlockData) GetTxList() []*Transaction {
	if m != nil {
		return m.TxList
	}
	return nil
}

type Block struct {
	Header               *BlockHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Data                 *BlockData   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	MultiSig             *Signature   `protobuf:"bytes,4,opt,name=multi_sig,json=multiSig,proto3" json:"multi_sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_2750a5e799b6b8ce, []int{2}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetData() *BlockData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetMultiSig() *Signature {
	if m != nil {
		return m.MultiSig
	}
	return nil
}

type TransactionData struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Nonce                int64    `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Amount               []byte   `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	GasPrice             []byte   `protobuf:"bytes,5,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit             []byte   `protobuf:"bytes,6,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PubKey               *Point   `protobuf:"bytes,8,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionData) Reset()         { *m = TransactionData{} }
func (m *TransactionData) String() string { return proto.CompactTextString(m) }
func (*TransactionData) ProtoMessage()    {}
func (*TransactionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_2750a5e799b6b8ce, []int{3}
}
func (m *TransactionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionData.Unmarshal(m, b)
}
func (m *TransactionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionData.Marshal(b, m, deterministic)
}
func (dst *TransactionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionData.Merge(dst, src)
}
func (m *TransactionData) XXX_Size() int {
	return xxx_messageInfo_TransactionData.Size(m)
}
func (m *TransactionData) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionData.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionData proto.InternalMessageInfo

func (m *TransactionData) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TransactionData) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TransactionData) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransactionData) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *TransactionData) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *TransactionData) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *TransactionData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TransactionData) GetPubKey() *Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type Transaction struct {
	Data                 *TransactionData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Sig                  *Signature       `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_2750a5e799b6b8ce, []int{4}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetData() *TransactionData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockHeader)(nil), "bean.block_header")
	proto.RegisterType((*BlockData)(nil), "bean.block_data")
	proto.RegisterType((*Block)(nil), "bean.block")
	proto.RegisterType((*TransactionData)(nil), "bean.transaction_data")
	proto.RegisterType((*Transaction)(nil), "bean.transaction")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_data_2750a5e799b6b8ce) }

var fileDescriptor_data_2750a5e799b6b8ce = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4d, 0x8b, 0xdb, 0x30,
	0x14, 0xc4, 0x76, 0x62, 0xc7, 0xcf, 0xe9, 0x76, 0x2b, 0xca, 0xa2, 0x7e, 0x40, 0xdd, 0x74, 0x0f,
	0x21, 0x94, 0x40, 0xd3, 0x9f, 0xd0, 0xcb, 0x42, 0xf7, 0xb0, 0x78, 0xe9, 0xad, 0x60, 0x94, 0x44,
	0xd8, 0x22, 0xb6, 0x65, 0xac, 0xe7, 0xc5, 0xf9, 0x05, 0xfd, 0x99, 0xbd, 0xf6, 0x67, 0x14, 0x3d,
	0x25, 0x6d, 0x76, 0xd3, 0xde, 0x3c, 0x4f, 0x6f, 0xc4, 0x68, 0x66, 0x0c, 0xb0, 0x15, 0x28, 0x96,
	0x6d, 0xa7, 0x51, 0xb3, 0xd1, 0x5a, 0x8a, 0xe6, 0x75, 0xbc, 0x93, 0x7b, 0x37, 0x98, 0xfd, 0xf4,
	0x61, 0xba, 0xae, 0xf4, 0x66, 0x97, 0x97, 0x52, 0x6c, 0x65, 0xc7, 0x38, 0x44, 0x0f, 0xb2, 0x33,
	0x4a, 0x37, 0xdc, 0x4b, 0xbd, 0xf9, 0x38, 0x3b, 0x42, 0xf6, 0x01, 0x9e, 0xb5, 0x9d, 0x7c, 0x50,
	0xba, 0x37, 0x79, 0x29, 0x4c, 0xc9, 0xfd, 0xd4, 0x9b, 0x4f, 0xb3, 0xe9, 0x71, 0x78, 0x23, 0x4c,
	0xc9, 0xde, 0x40, 0x5c, 0x08, 0x93, 0x57, 0xaa, 0x56, 0xc8, 0x03, 0x5a, 0x98, 0x14, 0xc2, 0xdc,
	0x5a, 0xcc, 0x5e, 0x81, 0xfd, 0xce, 0x7b, 0x23, 0xb7, 0x7c, 0x44, 0x67, 0x51, 0x21, 0xcc, 0x37,
	0x23, 0xb7, 0xec, 0x0a, 0xc2, 0x52, 0xaa, 0xa2, 0x44, 0x3e, 0xa6, 0x83, 0x03, 0x62, 0x6f, 0x21,
	0x46, 0x55, 0x4b, 0x83, 0xa2, 0x6e, 0x79, 0x98, 0x7a, 0xf3, 0x20, 0xfb, 0x3b, 0x60, 0xef, 0x20,
	0xa9, 0x65, 0xb7, 0xab, 0x64, 0xde, 0x69, 0x8d, 0x3c, 0x22, 0x2a, 0xb8, 0x51, 0xa6, 0x35, 0x5a,
	0x39, 0x38, 0x90, 0x5a, 0x69, 0xf8, 0x24, 0x0d, 0xac, 0x1c, 0x1c, 0x6e, 0x08, 0xb3, 0x4f, 0x70,
	0x51, 0xd1, 0xa3, 0xf3, 0xb6, 0x5f, 0xe7, 0x3b, 0xb9, 0xe7, 0x71, 0xea, 0xcd, 0x93, 0x55, 0xb2,
	0xb4, 0x2e, 0x2d, 0x5b, 0xad, 0x1a, 0xcc, 0xa6, 0x6e, 0xe5, 0xae, 0x5f, 0x7f, 0x95, 0x7b, 0x4b,
	0xa9, 0x55, 0xa3, 0xff, 0x30, 0x0c, 0x87, 0x34, 0x38, 0xa3, 0xd0, 0x8a, 0x63, 0x98, 0xd9, 0x3d,
	0x80, 0x33, 0xd8, 0xc6, 0x60, 0x2d, 0xc0, 0x21, 0xdf, 0xe8, 0xbe, 0xc1, 0xa3, 0xbf, 0x38, 0x7c,
	0xb1, 0x90, 0x2d, 0x20, 0xc2, 0x21, 0xaf, 0x94, 0x41, 0xee, 0xd3, 0xa5, 0x2f, 0xdc, 0xa5, 0xd8,
	0x89, 0xc6, 0x88, 0x0d, 0x2a, 0xdd, 0x64, 0x21, 0x0e, 0xb7, 0xca, 0xe0, 0xec, 0x87, 0x07, 0x63,
	0xba, 0x95, 0x2d, 0xac, 0x71, 0x56, 0x21, 0xc5, 0x91, 0xac, 0x98, 0x23, 0x9d, 0x66, 0x9a, 0x1d,
	0x36, 0xd8, 0x35, 0x8c, 0xac, 0x08, 0xca, 0x25, 0x59, 0x5d, 0x9e, 0x6e, 0xda, 0x79, 0x46, 0xa7,
	0xec, 0x23, 0xc4, 0x75, 0x5f, 0xa1, 0xca, 0x8d, 0x2a, 0x28, 0xa6, 0x64, 0xf5, 0xdc, 0xad, 0x1a,
	0x55, 0x34, 0x02, 0xfb, 0x4e, 0x66, 0x13, 0xda, 0xb8, 0x57, 0xc5, 0xec, 0x97, 0x07, 0x97, 0x27,
	0x0a, 0xdd, 0x2b, 0xff, 0x5f, 0xa2, 0x97, 0x30, 0x6e, 0x74, 0xb3, 0x91, 0xa4, 0x36, 0xc8, 0x1c,
	0x60, 0x17, 0xe0, 0xa3, 0x26, 0x59, 0x71, 0xe6, 0xa3, 0xb6, 0x6d, 0x10, 0x35, 0x79, 0xe4, 0x6a,
	0x72, 0x40, 0xc7, 0x76, 0xb5, 0x9d, 0xda, 0xc8, 0x43, 0x51, 0x6c, 0xa3, 0xee, 0x2c, 0x7e, 0x5c,
	0xbd, 0xf0, 0x49, 0xf5, 0x1e, 0xf5, 0x28, 0x7a, 0xda, 0xa3, 0x6b, 0x88, 0x8e, 0x15, 0x98, 0x9c,
	0x57, 0x20, 0x6c, 0x29, 0xca, 0xd9, 0x77, 0x48, 0x4e, 0x5e, 0xca, 0x16, 0x07, 0x37, 0x3d, 0x62,
	0x5c, 0x9d, 0x85, 0x75, 0xea, 0xe9, 0x7b, 0x08, 0xac, 0x9b, 0xfe, 0xbf, 0xdd, 0xb4, 0x67, 0xeb,
	0x90, 0x7e, 0xc8, 0xcf, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xf8, 0x44, 0xd3, 0xaf, 0x03,
	0x00, 0x00,
}
