// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bean/node.proto

package bean

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import mycrypto "BlockChainTest/mycrypto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerInfo struct {
	Pk                   *mycrypto.Point `protobuf:"bytes,1,opt,name=pk,proto3" json:"pk,omitempty"`
	Ip                   string          `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32           `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PeerInfo) Reset()         { *m = PeerInfo{} }
func (m *PeerInfo) String() string { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()    {}
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_1cbdc0aa6a53bb58, []int{0}
}
func (m *PeerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerInfo.Unmarshal(m, b)
}
func (m *PeerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerInfo.Marshal(b, m, deterministic)
}
func (dst *PeerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerInfo.Merge(dst, src)
}
func (m *PeerInfo) XXX_Size() int {
	return xxx_messageInfo_PeerInfo.Size(m)
}
func (m *PeerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerInfo proto.InternalMessageInfo

func (m *PeerInfo) GetPk() *mycrypto.Point {
	if m != nil {
		return m.Pk
	}
	return nil
}

func (m *PeerInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *PeerInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type PeerInfoList struct {
	List                 []*PeerInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PeerInfoList) Reset()         { *m = PeerInfoList{} }
func (m *PeerInfoList) String() string { return proto.CompactTextString(m) }
func (*PeerInfoList) ProtoMessage()    {}
func (*PeerInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_1cbdc0aa6a53bb58, []int{1}
}
func (m *PeerInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerInfoList.Unmarshal(m, b)
}
func (m *PeerInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerInfoList.Marshal(b, m, deterministic)
}
func (dst *PeerInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerInfoList.Merge(dst, src)
}
func (m *PeerInfoList) XXX_Size() int {
	return xxx_messageInfo_PeerInfoList.Size(m)
}
func (m *PeerInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_PeerInfoList proto.InternalMessageInfo

func (m *PeerInfoList) GetList() []*PeerInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type MinerInfo struct {
	Pk                   *mycrypto.Point `protobuf:"bytes,1,opt,name=pk,proto3" json:"pk,omitempty"`
	Peer                 *PeerInfo       `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MinerInfo) Reset()         { *m = MinerInfo{} }
func (m *MinerInfo) String() string { return proto.CompactTextString(m) }
func (*MinerInfo) ProtoMessage()    {}
func (*MinerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_1cbdc0aa6a53bb58, []int{2}
}
func (m *MinerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinerInfo.Unmarshal(m, b)
}
func (m *MinerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinerInfo.Marshal(b, m, deterministic)
}
func (dst *MinerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerInfo.Merge(dst, src)
}
func (m *MinerInfo) XXX_Size() int {
	return xxx_messageInfo_MinerInfo.Size(m)
}
func (m *MinerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MinerInfo proto.InternalMessageInfo

func (m *MinerInfo) GetPk() *mycrypto.Point {
	if m != nil {
		return m.Pk
	}
	return nil
}

func (m *MinerInfo) GetPeer() *PeerInfo {
	if m != nil {
		return m.Peer
	}
	return nil
}

func init() {
	proto.RegisterType((*PeerInfo)(nil), "bean.peer_info")
	proto.RegisterType((*PeerInfoList)(nil), "bean.peer_info_list")
	proto.RegisterType((*MinerInfo)(nil), "bean.miner_info")
}

func init() { proto.RegisterFile("bean/node.proto", fileDescriptor_node_1cbdc0aa6a53bb58) }

var fileDescriptor_node_1cbdc0aa6a53bb58 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0xb1, 0x0a, 0xc2, 0x30,
	0x14, 0x45, 0x49, 0x1a, 0x85, 0x3e, 0xa1, 0x85, 0x4c, 0xc1, 0xc5, 0xd0, 0x2e, 0x9d, 0x52, 0x50,
	0xfc, 0x0f, 0xc9, 0x0f, 0x14, 0xab, 0x11, 0x42, 0x6d, 0xf2, 0x88, 0x59, 0xfa, 0xf7, 0x92, 0x88,
	0x9d, 0x1c, 0x9c, 0x72, 0xc9, 0xbd, 0x1c, 0xce, 0x83, 0x7a, 0x34, 0x57, 0xd7, 0x3b, 0x7f, 0x37,
	0x0a, 0x83, 0x8f, 0x9e, 0xb3, 0xf4, 0xb1, 0xe7, 0xf3, 0x72, 0x0b, 0x0b, 0x46, 0xdf, 0x4f, 0x66,
	0xf9, 0x34, 0xcd, 0x05, 0x4a, 0x34, 0x26, 0x0c, 0xd6, 0x3d, 0x3c, 0x3f, 0x00, 0xc5, 0x49, 0x10,
	0x49, 0xba, 0xdd, 0xb1, 0x56, 0xdf, 0xb5, 0x42, 0x6f, 0x5d, 0xd4, 0x14, 0x27, 0x5e, 0x01, 0xb5,
	0x28, 0xa8, 0x24, 0x5d, 0xa9, 0xa9, 0x45, 0xce, 0x81, 0xa1, 0x0f, 0x51, 0x14, 0x92, 0x74, 0x1b,
	0x9d, 0x73, 0x73, 0x86, 0x6a, 0x25, 0x0e, 0x4f, 0xfb, 0x8a, 0xbc, 0x05, 0x96, 0x5e, 0x41, 0x64,
	0x91, 0xc1, 0x49, 0x46, 0xad, 0x1b, 0x9d, 0xcb, 0x46, 0x03, 0xcc, 0xd6, 0xfd, 0x6d, 0xd2, 0x02,
	0x4b, 0x84, 0xec, 0xf2, 0x8b, 0x99, 0xe2, 0xb8, 0xcd, 0x37, 0x9e, 0xde, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xcf, 0x7f, 0x45, 0xc7, 0x10, 0x01, 0x00, 0x00,
}
