// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bean/others.proto

package bean

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import crypto "BlockChainTest/crypto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Newcomer struct {
	Pk                   *crypto.Point `protobuf:"bytes,1,opt,name=pk,proto3" json:"pk,omitempty"`
	Ip                   string        `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32         `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Newcomer) Reset()         { *m = Newcomer{} }
func (m *Newcomer) String() string { return proto.CompactTextString(m) }
func (*Newcomer) ProtoMessage()    {}
func (*Newcomer) Descriptor() ([]byte, []int) {
	return fileDescriptor_others_9913f750d59594e0, []int{0}
}
func (m *Newcomer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Newcomer.Unmarshal(m, b)
}
func (m *Newcomer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Newcomer.Marshal(b, m, deterministic)
}
func (dst *Newcomer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Newcomer.Merge(dst, src)
}
func (m *Newcomer) XXX_Size() int {
	return xxx_messageInfo_Newcomer.Size(m)
}
func (m *Newcomer) XXX_DiscardUnknown() {
	xxx_messageInfo_Newcomer.DiscardUnknown(m)
}

var xxx_messageInfo_Newcomer proto.InternalMessageInfo

func (m *Newcomer) GetPk() *crypto.Point {
	if m != nil {
		return m.Pk
	}
	return nil
}

func (m *Newcomer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Newcomer) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type ListOfPeer struct {
	List                 []*Newcomer `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListOfPeer) Reset()         { *m = ListOfPeer{} }
func (m *ListOfPeer) String() string { return proto.CompactTextString(m) }
func (*ListOfPeer) ProtoMessage()    {}
func (*ListOfPeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_others_9913f750d59594e0, []int{1}
}
func (m *ListOfPeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfPeer.Unmarshal(m, b)
}
func (m *ListOfPeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfPeer.Marshal(b, m, deterministic)
}
func (dst *ListOfPeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfPeer.Merge(dst, src)
}
func (m *ListOfPeer) XXX_Size() int {
	return xxx_messageInfo_ListOfPeer.Size(m)
}
func (m *ListOfPeer) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfPeer.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfPeer proto.InternalMessageInfo

func (m *ListOfPeer) GetList() []*Newcomer {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Newcomer)(nil), "bean.newcomer")
	proto.RegisterType((*ListOfPeer)(nil), "bean.listOfPeer")
}

func init() { proto.RegisterFile("bean/others.proto", fileDescriptor_others_9913f750d59594e0) }

var fileDescriptor_others_9913f750d59594e0 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xc1, 0xaa, 0xc2, 0x30,
	0x10, 0x45, 0x49, 0xda, 0xf7, 0x78, 0x6f, 0x8a, 0x45, 0xb3, 0x0a, 0x82, 0x10, 0xba, 0xca, 0x2a,
	0x95, 0xfa, 0x1d, 0xa2, 0xe4, 0x0f, 0x6c, 0x19, 0x31, 0x54, 0x3b, 0x43, 0x1a, 0x90, 0xfe, 0xbd,
	0xb4, 0xc5, 0xdd, 0xcc, 0xb9, 0x17, 0xee, 0x81, 0x5d, 0x8b, 0xb7, 0xa1, 0xa6, 0xf4, 0xc0, 0x38,
	0x3a, 0x8e, 0x94, 0x48, 0xe5, 0x33, 0xda, 0x6f, 0xbb, 0x38, 0x71, 0xa2, 0xba, 0xc7, 0x69, 0xe5,
	0xd5, 0x19, 0xfe, 0x06, 0x7c, 0x77, 0xf4, 0xc2, 0xa8, 0x0e, 0x20, 0xb9, 0xd7, 0xc2, 0x08, 0x5b,
	0x34, 0x1b, 0xb7, 0x56, 0x1d, 0x53, 0x18, 0x92, 0x97, 0xdc, 0xab, 0x12, 0x64, 0x60, 0x2d, 0x8d,
	0xb0, 0xff, 0x5e, 0x06, 0x56, 0x0a, 0x72, 0xa6, 0x98, 0x74, 0x66, 0x84, 0xfd, 0xf1, 0xcb, 0x5d,
	0x1d, 0x01, 0x9e, 0x61, 0x4c, 0x97, 0xfb, 0x15, 0x31, 0xaa, 0x0a, 0xf2, 0xf9, 0xd3, 0xc2, 0x64,
	0xb6, 0x68, 0x4a, 0x37, 0x3b, 0xb8, 0xef, 0x9c, 0x5f, 0xb2, 0xf6, 0x77, 0xf1, 0x38, 0x7d, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x2a, 0x5f, 0xc1, 0x9d, 0xb4, 0x00, 0x00, 0x00,
}
