// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bean/serializable.proto

package bean

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import crypto "BlockChainTest/crypto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Serializable struct {
	Header               int32             `protobuf:"varint,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 []byte            `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	PubKey               *crypto.Point     `protobuf:"bytes,3,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Sig                  *crypto.Signature `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Serializable) Reset()         { *m = Serializable{} }
func (m *Serializable) String() string { return proto.CompactTextString(m) }
func (*Serializable) ProtoMessage()    {}
func (*Serializable) Descriptor() ([]byte, []int) {
	return fileDescriptor_serializable_2403b100fc6878ec, []int{0}
}
func (m *Serializable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Serializable.Unmarshal(m, b)
}
func (m *Serializable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Serializable.Marshal(b, m, deterministic)
}
func (dst *Serializable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Serializable.Merge(dst, src)
}
func (m *Serializable) XXX_Size() int {
	return xxx_messageInfo_Serializable.Size(m)
}
func (m *Serializable) XXX_DiscardUnknown() {
	xxx_messageInfo_Serializable.DiscardUnknown(m)
}

var xxx_messageInfo_Serializable proto.InternalMessageInfo

func (m *Serializable) GetHeader() int32 {
	if m != nil {
		return m.Header
	}
	return 0
}

func (m *Serializable) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Serializable) GetPubKey() *crypto.Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Serializable) GetSig() *crypto.Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func init() {
	proto.RegisterType((*Serializable)(nil), "bean.serializable")
}

func init() {
	proto.RegisterFile("bean/serializable.proto", fileDescriptor_serializable_2403b100fc6878ec)
}

var fileDescriptor_serializable_2403b100fc6878ec = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x4a, 0x4d, 0xcc,
	0xd3, 0x2f, 0x4e, 0x2d, 0xca, 0x4c, 0xcc, 0xc9, 0xac, 0x4a, 0x4c, 0xca, 0x49, 0xd5, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x49, 0x48, 0x09, 0x24, 0x17, 0x55, 0x16, 0x94, 0xe4, 0xeb,
	0x67, 0xa7, 0x56, 0x42, 0xc4, 0x95, 0xda, 0x19, 0xb9, 0x78, 0x90, 0x95, 0x0b, 0x89, 0x71, 0xb1,
	0x65, 0xa4, 0x26, 0xa6, 0xa4, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x79, 0x42,
	0x42, 0x5c, 0x2c, 0x49, 0xf9, 0x29, 0x95, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0xb6,
	0x90, 0x1a, 0x17, 0x7b, 0x41, 0x69, 0x52, 0x7c, 0x76, 0x6a, 0xa5, 0x04, 0xb3, 0x02, 0xa3, 0x06,
	0xb7, 0x11, 0xaf, 0x1e, 0xc4, 0x02, 0xbd, 0x82, 0xfc, 0xcc, 0xbc, 0x92, 0x20, 0xb6, 0x82, 0xd2,
	0x24, 0xef, 0xd4, 0x4a, 0x21, 0x65, 0x2e, 0xe6, 0xe2, 0xcc, 0x74, 0x09, 0x16, 0xb0, 0x1a, 0x41,
	0x98, 0x9a, 0xe2, 0xcc, 0xf4, 0xbc, 0xc4, 0x92, 0xd2, 0xa2, 0xd4, 0x20, 0x90, 0x6c, 0x12, 0x1b,
	0xd8, 0x41, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x88, 0x33, 0x0a, 0xc3, 0x00, 0x00,
	0x00,
}
